[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[phases.setup]
nixPkgs = ["python3"]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmds = ["uvicorn app.main:app --host 0.0.0.0 --port $PORT"]
